### ISSUE TITLE
Spiking/dropping sensor values in HA

### ISSUE THREAD

**Issue by michaelpiron** [plan-d-io/P1-dongle#15]
Every now and then, sensor values from the P1 dongle have spikes in Home Assistant.

Example: Utility meter Maximum demand current month:
Peak value of over 2.000.000.000 kW:
![image](https://github.com/plan-d-io/P1-dongle/assets/4469877/d7126ac7-6714-4055-b3d9-f459acd18b8b)

This also happens with sensor Utility meter total energy consumed:
The example below shows a short but deep drop in the normally increasing value, which blows up the whole energy cost calculation:
Drop in total energy consumed:
![image](https://github.com/plan-d-io/P1-dongle/assets/4469877/4d61160c-7703-4bab-a1e6-4baeec2bfdfd)

Resulting energy cost calculation:
![image](https://github.com/plan-d-io/P1-dongle/assets/4469877/ba7fd5d0-f529-439c-bb81-01bc80543fc4)

Firmware version 2.10:
![image](https://github.com/plan-d-io/P1-dongle/assets/4469877/8f97ee9d-3ecb-455e-a6c9-7d43d8db8dd6)

More debug info:
![image](https://github.com/plan-d-io/P1-dongle/assets/4469877/c9f0840b-3f3c-404c-8017-7ea74ebc26a6)

**Comment by Epyon01P** [comment]
Coincidentally, I noticed the same behaviour this week too. I have implemented a fix and pushed it to the develop branch. If you switch the release channel (under Dongle setttings in the webmin) you will fetch the latest version (v2.17). Your dongle will reboot multiple times, as I also switched to a new TLS certificate bundle. There is [one breaking change](https://github.com/plan-d-io/P1-dongle/releases/tag/V2.15), but it only concerns the EnergieID integration.

I will push it to the main channel next week.

**Comment by michaelpiron** [comment]
I deployed the new version on my dongle, things were running correctly for days, however today I got this:
![image](https://github.com/plan-d-io/P1-dongle/assets/4469877/dd7b65ea-5da3-47db-bdf9-e28e28111963)

**Comment by Epyon01P** [comment]
Implemented test fix in v2.19 on development branch.

**Comment by michaelpiron** [comment]
I still have issues:
![image](https://github.com/plan-d-io/P1-dongle/assets/4469877/ce48e267-8b59-4b20-b08a-d9d88804a702)

Issue started 15-Jan at noon:
![image](https://github.com/plan-d-io/P1-dongle/assets/4469877/e819e730-254b-4ee4-b8b1-2519d68255f8)

Syslog:
![image](https://github.com/plan-d-io/P1-dongle/assets/4469877/3d65e13d-884d-448c-87f5-2c72bad340e8)

**Comment by Epyon01P** [comment]
Added extra checks in v2.20.

**Comment by michaelpiron** [comment]
Issue still present in v2.2.
Today:
![image](https://github.com/plan-d-io/P1-dongle/assets/4469877/54bd023d-8e9a-491a-b0a5-16eeed394f99)

**Comment by Epyon01P** [comment]
Thanks. Seeing how it is now just a erroneous reading and not an overflow anymore gave me more insight in the problem. Test fix pushed to V2.21 on develop.

**Comment by jantielens** [comment]
Is this supposed to be fixed in v2.2? I'm still seeing gigantic spikes, for example here in my gas consumption. 
![image](https://github.com/plan-d-io/P1-dongle/assets/9884103/ebdef683-1c64-4f85-8561-67d04e2926bb)
(I hope these values are incorrect ;) )

**Comment by Epyon01P** [comment]
Are you also on develop, or on main?

**Comment by jantielens** [comment]
> Are you also on develop, or on main?

I'm on main.

**Comment by Epyon01P** [comment]
Should be fixed now in V2.23.
